apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.ReplicaCount }}
  selector:
    matchLabels:
      app: nginx
      project: roboshop
      component: frontend
  template: # from here onwards pod definition starts
    metadata:
      labels:
       app: nginx
       project: roboshop
       component: frontend
    spec:
      containers:
      - name: nginx
        image: "nginx:{{ .Values.deployment.imageVersion }}"
        ports:
        - containerPort: 80
